name: med_code
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=24.0
  - python-graphviz
  - pip:
    - python-dotenv
    - azure-ai-ml
    - plotly
    - nbformat
    - numpy
    - pandas
    - ipykernel
    - openpyxl
    - openai
    - nltk
    - anytree
    - tqdm
    - azure-ai-textanalytics==5.2.0
    - tiktoken
    