name: med_code
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=24.0
  - pip:
    - python-dotenv
    - azure-ai-ml
    - plotly
    - nbformat
    - numpy
    - pandas
    - ipykernel
    - openpyxl
    - openai